version: '3.8'

volumes:
  nostar-db-data:

services:
  nostar-app:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
        # Ensure that the variables in .env match the same variables in devcontainer.json
        - .env

    volumes:
      - ../..:/workspaces:cached
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  nostar-db:
    image: postgres:18-alpine
    restart: unless-stopped
    volumes:
      - nostar-db-data:/var/lib/postgresql
    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - .env


    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
